version: '3.8'

services:
  load_balancer:
    container_name: load_balancer
    networks:
      mynetwork:
        ipv4_address: 172.28.1.10
    tty: true
    stdin_open: true
    command: bash
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile

  server1:
    container_name: server1
    networks:
      mynetwork:
        ipv4_address: 172.28.1.11
    tty: true
    stdin_open: true
    command: bash
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile

  server2:
    container_name: server2
    networks:
      mynetwork:
        ipv4_address: 172.28.1.12
    tty: true
    stdin_open: true
    command: bash
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile

  client:
    container_name: client
    networks:
      mynetwork:
        ipv4_address: 172.28.1.20
    tty: true
    stdin_open: true
    command: bash
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24

